/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hospital;

import Paneles.Citas;
import Paneles.Pacientes;
import com.login.Login;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author marco
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setSize(1280, 720); // establecer el tamaño de la ventana
        initContent();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        fondopanelIz = new javax.swing.JPanel();
        nombreTitulo = new javax.swing.JLabel();
        fondoPacientes = new javax.swing.JPanel();
        textoPacientes = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fondoCitas = new javax.swing.JPanel();
        textoCitas = new javax.swing.JLabel();
        informacion = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JPanel();
        cerrarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new java.awt.BorderLayout());

        fondopanelIz.setBackground(new java.awt.Color(38, 41, 43));

        nombreTitulo.setBackground(new java.awt.Color(255, 255, 255));
        nombreTitulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        nombreTitulo.setForeground(new java.awt.Color(255, 255, 255));
        nombreTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreTitulo.setText("PACIENTES");

        fondoPacientes.setBackground(new java.awt.Color(95, 122, 219));

        textoPacientes.setBackground(new java.awt.Color(255, 255, 255));
        textoPacientes.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        textoPacientes.setForeground(new java.awt.Color(255, 255, 255));
        textoPacientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Personas.png"))); // NOI18N
        textoPacientes.setText("Crear, eliminar y actualizar");
        textoPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textoPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoPacientesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoPacientesLayout = new javax.swing.GroupLayout(fondoPacientes);
        fondoPacientes.setLayout(fondoPacientesLayout);
        fondoPacientesLayout.setHorizontalGroup(
            fondoPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        fondoPacientesLayout.setVerticalGroup(
            fondoPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Logo.png"))); // NOI18N

        fondoCitas.setBackground(new java.awt.Color(46, 50, 57));

        textoCitas.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        textoCitas.setForeground(new java.awt.Color(255, 255, 255));
        textoCitas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Calendario.png"))); // NOI18N
        textoCitas.setText("Agendar, eliminar e historial");
        textoCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textoCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoCitasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoCitasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoCitasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoCitasLayout = new javax.swing.GroupLayout(fondoCitas);
        fondoCitas.setLayout(fondoCitasLayout);
        fondoCitasLayout.setHorizontalGroup(
            fondoCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoCitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        fondoCitasLayout.setVerticalGroup(
            fondoCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        informacion.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        informacion.setForeground(new java.awt.Color(255, 255, 255));
        informacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        informacion.setText("Informacion...");

        btnCerrar.setBackground(new java.awt.Color(46, 50, 57));

        cerrarSesion.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.setToolTipText("");
        cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout fondopanelIzLayout = new javax.swing.GroupLayout(fondopanelIz);
        fondopanelIz.setLayout(fondopanelIzLayout);
        fondopanelIzLayout.setHorizontalGroup(
            fondopanelIzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondoCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondopanelIzLayout.createSequentialGroup()
                .addGroup(fondopanelIzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondopanelIzLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(fondopanelIzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(fondopanelIzLayout.createSequentialGroup()
                        .addGroup(fondopanelIzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondopanelIzLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondopanelIzLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        fondopanelIzLayout.setVerticalGroup(
            fondopanelIzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondopanelIzLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(nombreTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(fondoPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(fondoCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(fondopanelIz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondopanelIz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initContent() {
        ShowJPanel(new Pacientes());
    }
    
    private void ShowJPanel(JPanel p){
        p.setSize(938, 720);
        p.setLocation(0, 0);
    
        // Agregar el panel Pacientes al panel Dashboard
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    private void textoPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoPacientesMouseEntered
        informacion.setText("<html>Puedes crear nuevos registros de pacientes,<br>eliminar los que ya no necesites o<br>actualizar sus datos personales</html>");
    }//GEN-LAST:event_textoPacientesMouseEntered

    private void textoPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoPacientesMouseExited
        informacion.setText("Información...");
    }//GEN-LAST:event_textoPacientesMouseExited

    private void textoCitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoCitasMouseEntered
        informacion.setText("<html>Puedes agendar nuevas citas para tus pacientes,<br>eliminar las que se hayan cancelado o<br>consultar el historial de las citas realizadas.</html>");
    }//GEN-LAST:event_textoCitasMouseEntered

    private void textoCitasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoCitasMouseExited
        informacion.setText("Información...");
    }//GEN-LAST:event_textoCitasMouseExited

    private void cerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseEntered
        btnCerrar.setBackground(new Color(95, 122, 219));
    }//GEN-LAST:event_cerrarSesionMouseEntered

    private void cerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseExited
        btnCerrar.setBackground(new Color(46, 50, 57));
    }//GEN-LAST:event_cerrarSesionMouseExited

    Dashboard ventanaDashboard = this;
    Login ventanaLogin = new Login();
    private void cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseClicked
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de cerrar sesión?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            ventanaDashboard.dispose(); 
            ventanaLogin.setVisible(true); 
        } else {

        }
    }//GEN-LAST:event_cerrarSesionMouseClicked

    private void textoPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoPacientesMouseClicked
        nombreTitulo.setText("PACIENTES");
        fondoPacientes.setBackground(new Color(95, 122, 219));
        fondoCitas.setBackground(new Color(46, 50, 57));
        ShowJPanel(new Pacientes());
    }//GEN-LAST:event_textoPacientesMouseClicked

    private void textoCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoCitasMouseClicked
        nombreTitulo.setText("CITAS");
        fondoPacientes.setBackground(new Color(46, 50, 57));
        fondoCitas.setBackground(new Color(95, 122, 219));
        
        ShowJPanel(new Citas());
    }//GEN-LAST:event_textoCitasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnCerrar;
    private javax.swing.JLabel cerrarSesion;
    private javax.swing.JPanel content;
    private javax.swing.JPanel fondoCitas;
    private javax.swing.JPanel fondoPacientes;
    private javax.swing.JPanel fondopanelIz;
    private javax.swing.JLabel informacion;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombreTitulo;
    private javax.swing.JLabel textoCitas;
    private javax.swing.JLabel textoPacientes;
    // End of variables declaration//GEN-END:variables

    private void InitContent() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
