/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marco
 */
public class Citas extends javax.swing.JPanel {

    /**
     * Creates new form Citas
     */
    public Citas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCita = new javax.swing.JTable();
        tituloCrearCita = new javax.swing.JLabel();
        txtId_Pacientes = new javax.swing.JLabel();
        txtId_Doctor = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        boxIDPaciente = new javax.swing.JTextField();
        comboBoxIdDoctor = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        comboBoxHora = new javax.swing.JComboBox<>();
        comboBoxMin = new javax.swing.JComboBox<>();
        fondoCrear = new javax.swing.JPanel();
        btnCrear = new javax.swing.JLabel();
        tituloCrearCita1 = new javax.swing.JLabel();
        txtIDCita = new javax.swing.JLabel();
        boxIdCita = new javax.swing.JTextField();
        txtIdPacientesModi = new javax.swing.JLabel();
        comboBoxIdDoctorRe = new javax.swing.JComboBox<>();
        fondoBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JLabel();
        fondoCrearReceta = new javax.swing.JPanel();
        btnCrearReceta = new javax.swing.JLabel();
        fondoVerRecetas = new javax.swing.JPanel();
        btnVerReceta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRecetas = new javax.swing.JTable();
        fondoMostrarTodo = new javax.swing.JPanel();
        btnMostrarTodo = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        boxDescripcion = new javax.swing.JTextField();
        fondoBuscarReceta = new javax.swing.JPanel();
        btnBuscarReceta = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        tableCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Cita", "ID_Paciente", "Nombres_Paciente", "Apellidos Paciente", "ID_Doctor", "Nombres_Doctor", "Apellidos_Doctor", "Fecha", "Hora"
            }
        ));
        jScrollPane1.setViewportView(tableCita);

        tituloCrearCita.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        tituloCrearCita.setForeground(new java.awt.Color(38, 41, 43));
        tituloCrearCita.setText("CREAR CITA");

        txtId_Pacientes.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtId_Pacientes.setForeground(new java.awt.Color(38, 41, 43));
        txtId_Pacientes.setText("ID_Paciente:");

        txtId_Doctor.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtId_Doctor.setForeground(new java.awt.Color(38, 41, 43));
        txtId_Doctor.setText("ID_Doctor:");

        txtFecha.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(38, 41, 43));
        txtFecha.setText("Fecha:");

        txtHora.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtHora.setForeground(new java.awt.Color(38, 41, 43));
        txtHora.setText("Hora:");

        comboBoxIdDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        comboBoxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        comboBoxMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));

        fondoCrear.setBackground(new java.awt.Color(95, 122, 219));

        btnCrear.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrear.setText("CREAR");
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoCrearLayout = new javax.swing.GroupLayout(fondoCrear);
        fondoCrear.setLayout(fondoCrearLayout);
        fondoCrearLayout.setHorizontalGroup(
            fondoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoCrearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fondoCrearLayout.setVerticalGroup(
            fondoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tituloCrearCita1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        tituloCrearCita1.setForeground(new java.awt.Color(38, 41, 43));
        tituloCrearCita1.setText("CREAR RECETA");

        txtIDCita.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtIDCita.setForeground(new java.awt.Color(38, 41, 43));
        txtIDCita.setText("ID_Cita:");

        txtIdPacientesModi.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtIdPacientesModi.setForeground(new java.awt.Color(38, 41, 43));
        txtIdPacientesModi.setText("ID_Doctor:");

        comboBoxIdDoctorRe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        fondoBuscar.setBackground(new java.awt.Color(95, 122, 219));

        btnBuscar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("BUSCAR");
        btnBuscar.setToolTipText("");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBuscarLayout = new javax.swing.GroupLayout(fondoBuscar);
        fondoBuscar.setLayout(fondoBuscarLayout);
        fondoBuscarLayout.setHorizontalGroup(
            fondoBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fondoBuscarLayout.setVerticalGroup(
            fondoBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondoCrearReceta.setBackground(new java.awt.Color(95, 122, 219));

        btnCrearReceta.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnCrearReceta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearReceta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearReceta.setText("CREAR");
        btnCrearReceta.setToolTipText("");
        btnCrearReceta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearReceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearRecetaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearRecetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearRecetaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoCrearRecetaLayout = new javax.swing.GroupLayout(fondoCrearReceta);
        fondoCrearReceta.setLayout(fondoCrearRecetaLayout);
        fondoCrearRecetaLayout.setHorizontalGroup(
            fondoCrearRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrearReceta, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        fondoCrearRecetaLayout.setVerticalGroup(
            fondoCrearRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoCrearRecetaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrearReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoVerRecetas.setBackground(new java.awt.Color(95, 122, 219));

        btnVerReceta.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnVerReceta.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReceta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVerReceta.setText("VER RECETAS");
        btnVerReceta.setToolTipText("");
        btnVerReceta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerReceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerRecetaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerRecetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerRecetaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoVerRecetasLayout = new javax.swing.GroupLayout(fondoVerRecetas);
        fondoVerRecetas.setLayout(fondoVerRecetasLayout);
        fondoVerRecetasLayout.setHorizontalGroup(
            fondoVerRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoVerRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoVerRecetasLayout.setVerticalGroup(
            fondoVerRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoVerRecetasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVerReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tableRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Receta", "ID_Cita", "ID_Paciente", "Nombres_Paciente", "Apellidos_Paciente", "ID_Doctor", "Nombres_Doctor", "Apellidos_Doctor", "Fecha", "Hora"
            }
        ));
        jScrollPane2.setViewportView(tableRecetas);

        fondoMostrarTodo.setBackground(new java.awt.Color(95, 122, 219));

        btnMostrarTodo.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnMostrarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarTodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMostrarTodo.setText("VER CITAS");
        btnMostrarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarTodoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarTodoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarTodoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoMostrarTodoLayout = new javax.swing.GroupLayout(fondoMostrarTodo);
        fondoMostrarTodo.setLayout(fondoMostrarTodoLayout);
        fondoMostrarTodoLayout.setHorizontalGroup(
            fondoMostrarTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoMostrarTodoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoMostrarTodoLayout.setVerticalGroup(
            fondoMostrarTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoMostrarTodoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtDescripcion.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(38, 41, 43));
        txtDescripcion.setText("Descripción: ");

        fondoBuscarReceta.setBackground(new java.awt.Color(95, 122, 219));

        btnBuscarReceta.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnBuscarReceta.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarReceta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarReceta.setText("BUSCAR");
        btnBuscarReceta.setToolTipText("");
        btnBuscarReceta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarReceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarRecetaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarRecetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarRecetaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBuscarRecetaLayout = new javax.swing.GroupLayout(fondoBuscarReceta);
        fondoBuscarReceta.setLayout(fondoBuscarRecetaLayout);
        fondoBuscarRecetaLayout.setHorizontalGroup(
            fondoBuscarRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBuscarRecetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoBuscarRecetaLayout.setVerticalGroup(
            fondoBuscarRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoBuscarRecetaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscarReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txtIdPacientesModi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(comboBoxIdDoctorRe, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txtDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txtIDCita, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(boxIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(fondoCrearReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(fondoVerRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(fondoBuscarReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tituloCrearCita1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(comboBoxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(comboBoxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtId_Pacientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtId_Doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(boxIDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboBoxIdDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(51, 51, 51))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(tituloCrearCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(87, 87, 87))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(fondoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(fondoMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fondoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21))))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tituloCrearCita)
                        .addGap(20, 20, 20)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txtId_Pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(txtId_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFecha))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(boxIDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBoxIdDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboBoxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBoxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fondoCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fondoMostrarTodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fondoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addComponent(tituloCrearCita1)
                .addGap(23, 23, 23)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDCita)
                            .addComponent(boxIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdPacientesModi)
                            .addComponent(comboBoxIdDoctorRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(boxDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fondoCrearReceta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fondoBuscarReceta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fondoVerRecetas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        fondoCrear.setBackground(new Color(46, 50, 57));
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        fondoCrear.setBackground(new Color(95, 122, 219));
    }//GEN-LAST:event_btnCrearMouseExited

    private void btnCrearRecetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearRecetaMouseEntered
        fondoCrearReceta.setBackground(new Color(46, 50, 57));
    }//GEN-LAST:event_btnCrearRecetaMouseEntered

    private void btnCrearRecetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearRecetaMouseExited
        fondoCrearReceta.setBackground(new Color(95, 122, 219));
    }//GEN-LAST:event_btnCrearRecetaMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        fondoBuscar.setBackground(new Color(46, 50, 57));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        fondoBuscar.setBackground(new Color(95, 122, 219));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnVerRecetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRecetaMouseEntered
        fondoVerRecetas.setBackground(new Color(46, 50, 57));
    }//GEN-LAST:event_btnVerRecetaMouseEntered

    private void btnVerRecetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRecetaMouseExited
        fondoVerRecetas.setBackground(new Color(95, 122, 219));
    }//GEN-LAST:event_btnVerRecetaMouseExited

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        try {
            Conexion con = new Conexion();
            String idPaciente = boxIDPaciente.getText();
            String idDoctor = comboBoxIdDoctor.getSelectedItem().toString();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String fecha = sdf.format(dateChooser.getDate());
            String hora = comboBoxHora.getSelectedItem().toString();
            String min = comboBoxMin.getSelectedItem().toString();
            String horaCita = hora + ":" + min;

            String query = "INSERT INTO Citas (id_paciente, id_doctor, fecha, hora) VALUES (?, ?, ?, ?)";

            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, idPaciente);
            preparedStatement.setString(2, idDoctor);
            preparedStatement.setString(3, fecha);
            preparedStatement.setString(4, horaCita);

            preparedStatement.executeUpdate();
            boxIDPaciente.setText("");
            comboBoxIdDoctor.setSelectedIndex(0);
            dateChooser.setDate(null);
            comboBoxHora.setSelectedIndex(0);
            comboBoxMin.setSelectedIndex(0);
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnMostrarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTodoMouseClicked
        try {
            Conexion con = new Conexion();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT Citas.id_cita, Citas.id_paciente, Pacientes.nombres, Pacientes.apellidos, Citas.id_doctor, Doctores.nombres_doctor, Doctores.apellidos_doctor, Citas.fecha, Citas.hora FROM Citas JOIN Pacientes ON Citas.id_paciente = Pacientes.id_paciente JOIN Doctores ON Citas.id_doctor = Doctores.id_doctor");

            DefaultTableModel model = new DefaultTableModel(new Object[]{"ID_Cita", "ID_Paciente", "Nombres_Paciente", "Apellidos_Paciente", "ID_Doctor", "Nombres_Doctor", "Apellidos_Doctor", "Fecha", "Hora"}, 0);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("id_cita"), rs.getInt("id_paciente"), rs.getString("nombres"), rs.getString("apellidos"), rs.getInt("id_doctor"), rs.getString("nombres_doctor"), rs.getString("apellidos_doctor"), rs.getDate("fecha"), rs.getTime("hora")});
            }
            tableCita.setModel(model);
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMostrarTodoMouseClicked

    private void btnMostrarTodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTodoMouseEntered
        fondoMostrarTodo.setBackground(new Color(46, 50, 57));
    }//GEN-LAST:event_btnMostrarTodoMouseEntered

    private void btnMostrarTodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTodoMouseExited
        fondoMostrarTodo.setBackground(new Color(95, 122, 219));
    }//GEN-LAST:event_btnMostrarTodoMouseExited

    private void btnVerRecetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRecetaMouseClicked
        try {
            Conexion con = new Conexion();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT Recetas.id_receta, Recetas.id_cita, Pacientes.nombres, Pacientes.apellidos, Recetas.id_doctor, Doctores.nombres_doctor, Doctores.apellidos_doctor, Recetas.fecha, Recetas.hora FROM Recetas JOIN Citas ON Recetas.id_cita = Citas.id_cita JOIN Pacientes ON Citas.id_paciente = Pacientes.id_paciente JOIN Doctores ON Recetas.id_doctor = Doctores.id_doctor");

            DefaultTableModel model = new DefaultTableModel(new Object[]{"ID_Receta", "ID_Cita", "Nombres_Paciente", "Apellidos_Paciente", "ID_Doctor", "Nombres_Doctor", "Apellidos_Doctor", "Fecha", "Hora"}, 0);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("id_receta"), rs.getInt("id_cita"), rs.getString("nombres"), rs.getString("apellidos"), rs.getInt("id_doctor"), rs.getString("nombres_doctor"), rs.getString("apellidos_doctor"), rs.getDate("fecha"), rs.getTime("hora")});
            }
            tableRecetas.setModel(model);
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnVerRecetaMouseClicked

    private void btnBuscarRecetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarRecetaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarRecetaMouseClicked

    private void btnBuscarRecetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarRecetaMouseEntered
        fondoBuscarReceta.setBackground(new Color(46, 50, 57));
    }//GEN-LAST:event_btnBuscarRecetaMouseEntered

    private void btnBuscarRecetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarRecetaMouseExited
        fondoBuscarReceta.setBackground(new Color(95, 122, 219));
    }//GEN-LAST:event_btnBuscarRecetaMouseExited

    private void btnCrearRecetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearRecetaMouseClicked
        try {
            Conexion con = new Conexion();
            String idCita = boxIdCita.getText();
            String idDoctor = comboBoxIdDoctorRe.getSelectedItem().toString();
            String descripcion = boxDescripcion.getText();

            String query = "INSERT INTO Recetas (id_cita, id_doctor, fecha, hora, descripcion) VALUES (?, ?, CURRENT_DATE(), CURRENT_TIME(), ?)";

            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, idCita);
            preparedStatement.setString(2, idDoctor);
            preparedStatement.setString(3, descripcion);

            preparedStatement.executeUpdate();
            boxIdCita.setText("");
            comboBoxIdDoctorRe.setSelectedIndex(0);
            boxDescripcion.setText("");
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCrearRecetaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JTextField boxDescripcion;
    private javax.swing.JTextField boxIDPaciente;
    private javax.swing.JTextField boxIdCita;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnBuscarReceta;
    private javax.swing.JLabel btnCrear;
    private javax.swing.JLabel btnCrearReceta;
    private javax.swing.JLabel btnMostrarTodo;
    private javax.swing.JLabel btnVerReceta;
    private javax.swing.JComboBox<String> comboBoxHora;
    private javax.swing.JComboBox<String> comboBoxIdDoctor;
    private javax.swing.JComboBox<String> comboBoxIdDoctorRe;
    private javax.swing.JComboBox<String> comboBoxMin;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JPanel fondoBuscar;
    private javax.swing.JPanel fondoBuscarReceta;
    private javax.swing.JPanel fondoCrear;
    private javax.swing.JPanel fondoCrearReceta;
    private javax.swing.JPanel fondoMostrarTodo;
    private javax.swing.JPanel fondoVerRecetas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCita;
    private javax.swing.JTable tableRecetas;
    private javax.swing.JLabel tituloCrearCita;
    private javax.swing.JLabel tituloCrearCita1;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtIDCita;
    private javax.swing.JLabel txtIdPacientesModi;
    private javax.swing.JLabel txtId_Doctor;
    private javax.swing.JLabel txtId_Pacientes;
    // End of variables declaration//GEN-END:variables
}
